name: Generate Smart Contract Deployment Link

on:
    pull_request:
        branches:
            - main
    # push:
    #     branches:
    #         - main

jobs:
    link-gen:
        name: "Generate Deployment Link"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Node
              uses: actions/setup-node@v4

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Generate Deploy Link & Add to Summary
              run: |
                    npx thirdweb@latest deploy --file src/contracts/ -k ${{secrets.THIRDWEB_API_KEY}} --ci &> tempLog.txt
                    DEPLOY_LINK=$(cat tempLog.txt | grep -Eo "https://[^ ]+")
                    echo "${DEPLOY_LINK}" >> $GITHUB_STEP_SUMMARY