name: Pull request analysis

on:
    pull_request:
        branches:
            - main

jobs:
    analyze-code:
        name: "Analyze Code"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: "Install Node"
              uses: actions/setup-node@v4

            - name: "Install dependencies"
              run: yarn install

            - name: "Run Linter"
              run: yarn solhint --config .solhint.json src/**/*.sol --max-warnings 0

            - name: "Run Slither"
              uses: crytic/slither-action@v0.4.0
              with:
                fail-on: all
                
    run-tests:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1.2.0

            - name: "Run tests"
              run: forge test -vvv
              env:
                FOUNDRY_PROFILE: ci


            